In [5]:
import binascii
import serial
import os
import cv2
from  matplotlib import pyplot as plt

def run_action(cmd):
    ser = serial.Serial("/dev/ttyPS0", 9600, timeout=5)
    cnt_err = 0
    while 1:
        test_read = ser.read()
        # print('test_read', test_read)
        cnt_err += 1
        if test_read== b'\xa3' or cnt_err == 50:
            break
    
    if cnt_err == 50:
        print('can not get REQ')
    else:
        print('read REQ finished!')
        ser.write(cmd2data(cmd))
        print('send action ok!')
    ser.close()
    
def crc_calculate(package):
    crc = 0
    for hex_data in package:

        b2 = hex_data.to_bytes(1, byteorder='little')
        crc = binascii.crc_hqx(b2, crc)

    return [(crc >> 8), (crc & 255)]    # 校验位两位

def cmd2data(cmd):
    cnt=0
    cmd_list=[]
    for i in cmd:
        cnt+=1
        cmd_list+=[ord(i)]
    cmd_list=[0xff,0xff]+[(cnt+5)>>8,(cnt+5)&255]+[0x01,(cnt+1)&255,0x03]+cmd_list
    cmd_list=cmd_list+crc_calculate(cmd_list)
    return cmd_list

def wait_req():
    ser = serial.Serial("/dev/ttyPS0", 9600, timeout=5)
    while 1:
        test_read=ser.read()
        if test_read== b'\xa3' :
            print('read REQ finished!') 
            break
def getpos():
    os.system('fswebcam  --no-banner --save temp.jpg -d /dev/video0 2> /dev/null')
    image = cv2.imread('temp.jpg')
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    ret,thres = cv2.threshold(gray, 60, 255, 0)
    edges = cv2.Canny(thres, 50, 150)
    minLineLength = 130
    maxLineGap = 20
    lines = cv2.HoughLinesP(edges, rho=1, theta=3.1415926/180, threshold=40, minLineLength=minLineLength, maxLineGap=maxLineGap)
    for line in lines:
        print(line)
        for x1, y1, x2, y2 in line:
            k = (y2 - y1) / (x2 - x1)
            if k > 4:
                continue
            print(k)
            cv2.line(image, (x1, y1), (x2, y2), (255, 0, 0), 2)
    # plt.imshow(thres)
#     plt.imshow(image)
#     plt.show()
    return k
b_thres = 10
s_thres = 0.05

In [6]:
os.system('sh ./stop_sys_ttyPS0.sh')

0

In [7]:
flag1 = False
flag2 = False

while not (flag1 and flag2):
    s = getpos()
    flag1 = False
    flag2 = False
    
    if b < -b_thres:
        wait_req()
        run_action('turn003L')
    elif b > b_thres:
        wait_req()
        run_action('turn003R')
    else:
        flag1 = True
        
    if s < s_thres:
        wait_req()
        run_action('Left02move')
    elif s > -s_thres:
        wait_req()
        run_action('Right02move')
    else:
        flag2 = True

[[144 438 293 478]]
0.268456375839
[[148 426 292 470]]
0.305555555556
[[136 443 292 479]]
0.230769230769
[[111 469 278 461]]
-0.0479041916168
[[115 468 262 450]]
-0.122448979592
[[115 473 290 461]]
-0.0685714285714
[[142 434 292 471]]
0.246666666667
[[142 433 274 463]]
0.227272727273


NameError: name 'b' is not defined

In [25]:
wait_req()
run_action('headleft')
#头左

read REQ finished!
read REQ finished!
send action ok!


In [26]:
wait_req()
run_action('headright')
#头右

read REQ finished!
read REQ finished!
send action ok!


In [27]:
wait_req()
run_action('Stand')
#站立

read REQ finished!
read REQ finished!
send action ok!


In [11]:
wait_req()
run_action('slow03')
#慢走一格

read REQ finished!
read REQ finished!
send action ok!


In [24]:
wait_req()
run_action('slowForward01')
wait_req()
run_action('Forwalk02')
#慢走一格

read REQ finished!
read REQ finished!
send action ok!
read REQ finished!
read REQ finished!
send action ok!


In [10]:
wait_req()
run_action('UpBridge01')
#上台阶

read REQ finished!
read REQ finished!
send action ok!


In [18]:
wait_req()
run_action('slowBackward01')
#慢退一步

read REQ finished!
read REQ finished!
send action ok!


In [6]:
def f1L(): #左转
    run_action('turn005L')
    wait_req()
    run_action('turn005L')
    wait_req()
    run_action('turn005L')
    wait_req()
    run_action('Stand')

In [23]:
def f1R():#右转
    run_action('turn005R')
    wait_req()
    run_action('turn005R')
    wait_req()
    run_action('turn005R')
    wait_req()
    run_action('Stand')

In [7]:
f1L()

read REQ finished!
send action ok!
read REQ finished!
read REQ finished!
send action ok!
read REQ finished!
read REQ finished!
send action ok!
read REQ finished!
read REQ finished!
send action ok!


In [28]:
wait_req()
run_action('Stand')

KeyboardInterrupt: 